services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicboxd
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env.local
    depends_on:
      - database
  database:
    image: mongo
    container_name: musicboxd_mongo
    ports:
      - "27017:2017"