services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicboxd
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - database
      - socket
  socket:
    build:
      context: socket
      dockerfile: Dockerfile
    container_name: musicboxd_socket
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
  database:
    image: mongo
    container_name: musicboxd_mongo
    ports:
      - "27017:2017"